[package]
name = "rio"
version = "0.0.5"
authors = ["Raphael Amorim <rapha850@gmail.com>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/raphamorim/rio"
documentation = "https://github.com/raphamorim/rio#readme"
description = "Rio terminal app"

[dependencies]
base64 = "0.21.0"
bitflags = "2.0.2"
bytemuck = { workspace = true }
colors = { path = "../colors" }
config = { path = "../config" }
copypasta = { version = "0.8.1", default-features = false }
dirs = "5.0"
glyph_brush = "0.7.7"
image = { version = "0.24.5", default-features = false, features = ["ico"] }
lazycell = "1"
libc = "0.2.141"
log = { workspace = true }
mio = "0.6.20"
mio-extras = "2"
parking_lot = "0.12"
serde = { workspace = true }
sugarloaf = { path = "../sugarloaf" }
teletypewriter = { workspace = true }
tokio = { version = "1.26.0", features = ["full"] }
unicode-width = "0.1.5"
vte = { version = "0.11.1", default-features = false }
wgpu = { workspace = true }
winit = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2.2"

[package.metadata.bundle]
name = "Rio"
identifier = "com.raphaelamorim.rio"
icon = ["src/screen/window/resources/images/logo-macos.ico"]
resources = ["src/screen/window/resources"]
copyright = "Copyright (c) Raphael Amorim 2023. All rights reserved."
category = "Developer Tool"
osx_minimum_system_version = "10.14"
short_description = "A terminal application"
long_description = """
Rio is a terminal built to run everywhere, as a native desktop applications by Rust/WebGPU or even in the browsers powered by WebAssembly/WebGPU. More info in https://raphamorim.io/rio
"""

[features]
x11 = [
  "copypasta/x11"
]
wayland = [
  "copypasta/wayland"
]
